apiVersion: v1
kind: Namespace
metadata:
  name: tdengine
---
apiVersion: v1
kind: Service
metadata:
  name: tdengine
  namespace: tdengine
  labels:
    app: tdengine
spec:
  type: NodePort
  ports:
  - port: 6030
    targetPort: 6030
    nodePort: 30630
    name: tdengine
  - port: 6041
    targetPort: 6041
    nodePort: 30641
    name: websocket
  selector:
    app: tdengine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tdengine
  namespace: tdengine
  labels:
    app: tdengine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tdengine
  template:
    metadata:
      labels:
        app: tdengine
    spec:
      containers:
      - name: tdengine
        image: docker.io/tdengine/tdengine:3.3.5.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6030
          name: tdengine
        - containerPort: 6041
          name: websocket
        env:
        - name: TAOS_CACHE_SIZE
          value: "512"
        - name: TAOS_WAL_LEVEL
          value: "1"
        volumeMounts:
        - name: tdengine-data
          mountPath: /var/lib/taos
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 2Gi
      volumes:
      - name: tdengine-data
        emptyDir: {}
