// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/user","id":"1"},"2":{"path":"/user/login","parentId":"1","id":"2"},"3":{"path":"/user/register","parentId":"1","id":"3"},"4":{"path":"/user/forgot-password","parentId":"1","id":"4"},"5":{"path":"/create_tenant","id":"5"},"6":{"path":"/","id":"6"},"7":{"path":"/","redirect":"/dashboard","parentId":"6","id":"7"},"8":{"path":"/dashboard","parentId":"6","id":"8"},"9":{"path":"/tenant","parentId":"6","id":"9"},"10":{"path":"/users","parentId":"6","id":"10"},"11":{"path":"/site","parentId":"6","id":"11"},"12":{"path":"/namespace","parentId":"6","id":"12"},"13":{"path":"/organization","parentId":"6","id":"13"},"14":{"path":"/department","parentId":"6","id":"14"},"15":{"path":"/resources","parentId":"6","id":"15"},"16":{"path":"/resources/crd","parentId":"15","id":"16"},"17":{"path":"/resources/operator","parentId":"15","id":"17"},"18":{"path":"/resources/controller","parentId":"15","id":"18"},"19":{"path":"/settings","parentId":"6","id":"19"},"20":{"path":"/settings/system","parentId":"19","id":"20"},"21":{"path":"/settings/role","parentId":"19","id":"21"},"22":{"path":"/settings/user-role","parentId":"19","id":"22"},"23":{"path":"/settings/role-menu","parentId":"19","id":"23"},"24":{"path":"/device","parentId":"6","id":"24"},"25":{"path":"/device/product","parentId":"24","id":"25"},"26":{"path":"/device/driver","parentId":"24","id":"26"},"27":{"path":"/device/node","parentId":"24","id":"27"},"28":{"path":"/device/device","parentId":"24","id":"28"},"29":{"path":"/device/group","parentId":"24","id":"29"},"30":{"path":"/device/instance","parentId":"24","id":"30"},"31":{"path":"/config","parentId":"6","id":"31"},"32":{"path":"/config/configmap","parentId":"31","id":"32"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__user__Login" */'@/pages/user/Login.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__user__Register" */'@/pages/user/Register.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__user__ForgotPassword" */'@/pages/user/ForgotPassword.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__tenant__Create" */'@/pages/tenant/Create.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "layouts__BasicLayout" */'@/layouts/BasicLayout.tsx')),
'7': React.lazy(() => import('./EmptyRoute')),
'8': React.lazy(() => import(/* webpackChunkName: "p__Dashboard" */'@/pages/Dashboard.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__tenant__List" */'@/pages/tenant/List.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__user__List" */'@/pages/user/List.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__site__List" */'@/pages/site/List.tsx')),
'12': React.lazy(() => import(/* webpackChunkName: "p__namespace__List" */'@/pages/namespace/List.tsx')),
'13': React.lazy(() => import(/* webpackChunkName: "p__organization__List" */'@/pages/organization/List.tsx')),
'14': React.lazy(() => import(/* webpackChunkName: "p__department__List" */'@/pages/department/List.tsx')),
'15': React.lazy(() => import('./EmptyRoute')),
'16': React.lazy(() => import(/* webpackChunkName: "p__resource__crd__List" */'@/pages/resource/crd/List.tsx')),
'17': React.lazy(() => import(/* webpackChunkName: "p__resource__operator__List" */'@/pages/resource/operator/List.tsx')),
'18': React.lazy(() => import(/* webpackChunkName: "p__resource__controller__List" */'@/pages/resource/controller/List.tsx')),
'19': React.lazy(() => import('./EmptyRoute')),
'20': React.lazy(() => import(/* webpackChunkName: "p__settings__SystemConfig" */'@/pages/settings/SystemConfig.tsx')),
'21': React.lazy(() => import(/* webpackChunkName: "p__role__List" */'@/pages/role/List.tsx')),
'22': React.lazy(() => import(/* webpackChunkName: "p__user-role__List" */'@/pages/user-role/List.tsx')),
'23': React.lazy(() => import(/* webpackChunkName: "p__role-menu__List" */'@/pages/role-menu/List.tsx')),
'24': React.lazy(() => import('./EmptyRoute')),
'25': React.lazy(() => import(/* webpackChunkName: "p__device__product__List" */'@/pages/device/product/List.tsx')),
'26': React.lazy(() => import(/* webpackChunkName: "p__device__driver__List" */'@/pages/device/driver/List.tsx')),
'27': React.lazy(() => import(/* webpackChunkName: "p__device__node__List" */'@/pages/device/node/List.tsx')),
'28': React.lazy(() => import(/* webpackChunkName: "p__device__device__List" */'@/pages/device/device/List.tsx')),
'29': React.lazy(() => import(/* webpackChunkName: "p__device__group__List" */'@/pages/device/group/List.tsx')),
'30': React.lazy(() => import(/* webpackChunkName: "p__device__instance__List" */'@/pages/device/instance/List.tsx')),
'31': React.lazy(() => import('./EmptyRoute')),
'32': React.lazy(() => import(/* webpackChunkName: "p__config__config_map__List" */'@/pages/config/config_map/List.tsx')),
},
  };
}
